# Generated by Django 3.1.5 on 2021-01-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_discord_connector', '0010_auto_20201120_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordclient',
            name='name_enforcement_schema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
